// HARP configuration — the single source of truth for the methodology + branding.
// Thresholds are deliberate STARTING POINTS, not professional standards. Tune freely.
window.HARP = window.HARP || {};

HARP.config = {
  // Firm branding shown on the client-facing report. Replace with real Brookhaven assets.
  branding: {
    firmName: 'Brookhaven',
    tagline: 'Integrated Wealth Strategies',
    contact: { phone: '', email: '', website: '', address: '' },
    logoUrl: '', // path to a logo (SVG/PNG) once provided; falls back to the firm name
    colors: { primary: '#0b3a8a', accent: '#1f6feb' },
    // Client-facing disclosures printed at the foot of every page. Covers the two proprietary data
    // sources HARP is built on — Nitrogen/Riskalyze (investment analytics) and the BrookHaven Tax
    // Strategy Calculator (tax figures) — plus the standard not-advice / no-guarantee language. This is
    // the SINGLE source of truth for report disclosures; edit here, not in report.js.
    disclaimer:
      'This report was prepared by Brookhaven for informational and educational purposes only. It does ' +
      'not constitute investment, tax, legal, or insurance advice, nor an offer or solicitation to buy or ' +
      'sell any security. Investment risk analytics — including the Risk Number®, portfolio GPA, asset ' +
      'allocation, and projected 6-month ranges — are generated by Nitrogen (formerly Riskalyze) and used ' +
      'under Brookhaven’s subscription; the Risk Number® is a patented quantitative measure, and projected ' +
      'ranges are probabilistic estimates, not guarantees. Tax figures, projected liabilities, and strategy ' +
      'savings are estimates produced by the BrookHaven Tax Strategy Calculator from the information ' +
      'provided; they are not a filed tax return, not a guarantee of results, and not a substitute for ' +
      'advice from a qualified tax professional. All figures depend on the accuracy of the inputs and on ' +
      'configurable assumptions; actual results will vary and past performance does not indicate future ' +
      'results. Consult the appropriate licensed professional before acting. Advisory services offered ' +
      'through Brookhaven; see Form ADV for details.'
  },

  // Investment concentration
  singleStockConcentrationPct: 20,   // flag any one stock above this % of the portfolio (single-name risk)
  sectorConcentrationPct: 30,        // flag any one sector above this % of the portfolio (sector over-allocation)
  // Sectors that are diversified or non-equity — excluded from the concentration flags, since an
  // S&P 500 fund or a cash balance is not single-name or sector risk.
  nonConcentratingSectors: ['Diversified / Fund', 'Cash & Equivalents'],
  // Investment-category finding score weights (how hard each moves the Investments gauge). Concentration
  // = critical; performance / embedded-gains = moderate. Tuned so 1 critical ~ mid-yellow, 2 ~ red.
  investmentWeights: { critical: 33, moderate: 10 },

  // Investment performance: a growth-goal, 100%-stock portfolio's most recent full-year return is
  // compared to the S&P 500's long-run average (~10%/yr). This is context only, not a scored ding, and
  // is skipped for mixed portfolios (which reasonably aim for less). See performance.js / income.js.
  performance: {
    benchmarkName: 'S&P 500',
    tolerancePct: 0,              // any underperformance vs the benchmark flags
    trailing3yr: {
      annualizedPct: 10.0         // S&P 500 long-run average annual return
    }
  },

  // Investment risk tolerance — Nitrogen / Riskalyze "Risk Number" (1-99). The client's risk-tolerance
  // number is compared to their current portfolio's risk number; the GAP drives the Investments risk
  // assessment. This REPLACED the age-based (110-minus-age) allocation check. Direction matters:
  //   • Portfolio riskier than tolerance (over-risk)  -> critical past criticalGap, any goal.
  //   • Portfolio tamer than tolerance (under-risk)   -> critical only for a GROWTH goal; else moderate.
  risk: {
    scaleMax: 99,        // Nitrogen Risk Number scale (1-99)
    alignedBand: 10,     // |portfolio - tolerance| within this => aligned (no concern)
    criticalGap: 20,     // a gap beyond this => critical; between alignedBand and this => moderate
    // Investments CATEGORY score is a SMOOTH function of the alignment gap (|portfolio - tolerance|), not
    // coarse finding-count steps: a portfolio sitting right on the client's tolerance is near-perfect and
    // the score falls proportionally with the gap. Calibrated to intent: gap 1 => ~98 ("almost perfect"),
    // gap 20 => ~68 (a real but moderate concern), gap 50 => ~20. score = 100 - min(1, gap/maxGap) * span.
    alignScoreMaxGap: 50,   // the gap treated as "as misaligned as it gets" on the 1-99 scale
    alignScoreSpan: 80,     // how many points a full-max gap removes from a perfect 100
    underRiskGoalRelief: 0.6, // under-risk (portfolio tamer than tolerance) for a non-growth goal is softened
    // Risk Number -> plain band label (matches the intake questionnaire's bands).
    bands: [[33, 'Conservative'], [66, 'Moderate'], [99, 'Aggressive']]
  },

  // Supporting Riskalyze data-point signals for the Investments verdict (beyond the tolerance/portfolio
  // alignment). These are Riskalyze's OWN outputs — no HARP re-calculation.
  riskalyze: {
    // Portfolio GPA (Riskalyze's risk-adjusted quality grade): C is a moderate concern, D/F critical,
    // A/B a clean pass.
    gpaModerate: ['C'],
    gpaCritical: ['D', 'F'],
    // Weighted expense ratio (%): a cost signal. At/below "low" reads as a low-cost portfolio (good).
    expenseLowPct: 0.40,
    expenseModeratePct: 0.75,
    expenseCriticalPct: 1.25
  },

  // RETIRED (superseded by `risk` above / js/engine/risk.js): the age-based "prudent" allocation
  // guideline, ~(base - age)% in stocks. Kept for reference in case allocation.js is ever re-wired.
  allocation: { base: 110, moderateDeviation: 25, criticalDeviation: 50 },

  // Assumed retirement age — used to derive remaining working years from the client's age (insurance).
  retirementAge: 65,

  // Long-run NOMINAL return assumptions by asset class (%/yr). Used to estimate a portfolio's expected
  // return from its Riskalyze allocation, which drives the retirement projection. Deliberate starting points.
  assetClassReturns: { stocks: 7.0, bonds: 3.0, cash: 1.0, other: 5.0 },

  // Retirement readiness — a TRANSPARENT deterministic projection (grow to retirement, then draw an
  // inflation-adjusted need through longevity). Not a Monte Carlo; a real probability would come from
  // Riskalyze's Retirement Maps if/when that scrape is wired.
  retirement: {
    longevityAge: 92,        // plan the money to last through this age
    inflationPct: 2.5,       // withdrawals grow with inflation each year
    shortfallModerateYears: 5,   // runs out within this many years of longevity => moderate; sooner => critical
    riskReturn: { base: 2.0, span: 8.0 }  // fallback expected return when no allocation: base + (Risk#/99)*span
  },

  // Income goal: how far portfolio income can fall below the withdrawal need before it's critical.
  income: { criticalShortfallPct: 25 },

  // Embedded / unrealized gains — assessed cumulatively across the portfolio (gains and losses net).
  // A holding counts as "large" when its gain is over embeddedGainPct of cost AND at least minGainAmount;
  // one consolidated flag is raised when a large gain exists and the net embedded gain is positive.
  gains: {
    embeddedGainPct: 50,      // a stock's unrealized gain > this % of its cost basis is "large"
    minGainAmount: 25000      // ...and only when that stock's dollar gain is at least this material
  },

  // Insurance adequacy: total face value (payout) vs liabilities and vs future income (income x years to
  // retirement), plus policy age. Each is its own finding; the CATEGORY score uses the (C,M) rubric below.
  insurance: {
    significantShortfallBand: 0.5,   // payout covering < half a need => critical, else moderate (liabilities & future income)
    defaultYearsToRetirement: 20,    // remaining working years assumed when not provided
    policyAgeModerateYears: 7,        // policy issued / last reviewed >= this (and < critical) => moderate
    policyAgeCriticalYears: 10,       // >= this => critical
    // Insurance CATEGORY score by (criticals C, moderates M); overrides the generic per-finding scoring.
    categoryScore: { none: 15, c2: 25, c1m1: 50, c1: 65, m2: 65, m1: 85, ok: 100 }
  },

  // Tax health — now driven by the BrookHaven Tax Strategy Calculator's own outputs (js/engine/tax.js),
  // NOT by HARP re-deriving anything from a 1040 or by bucket diversification (both retired, mirroring how
  // Investments defers to Nitrogen). The tax CATEGORY score falls as the unrealized-savings ratio
  // (identified savings ÷ current projected tax) rises: a large, reducible tax bill is a real, scored gap
  // — with the calculator's strategies as the attached plan to close it.
  tax: {
    savingsModerateRatio: 0.10,   // >10% of the projected tax reducible => a moderate opportunity (warn)
    savingsCriticalRatio: 0.30,   // >30% reducible => a critical unrealized opportunity (risk)
    savingsScoreSpan: 70,         // category score = 100 - min(1, ratio) * span  (ratio 0 => 100, 0.8 => ~44)
    highMarginalPct: 32           // at/above this federal marginal bracket, add a planning-leverage note
  },

  // Accounting / 1040
  accounting: {
    highEffectiveRatePct: 25,        // effective tax rate above this prompts a tax-efficiency note
    // IRS standard deduction by filing status (tax year 2025, OBBBA-adjusted). Refresh each tax year.
    standardDeductions: {
      'Single': 15750,
      'Married filing jointly': 31500,
      'Married filing separately': 15750,
      'Head of household': 23625
    },
    // "In a high bracket on only the standard deduction" severity: flag at/above the moderate bracket,
    // critical at/above the critical bracket. The bracket is read off AGI (no tax is calculated).
    bracketModerateMin: 24,
    bracketCriticalMin: 35,
    lowAgiModerateBand: 1.1,         // AGI below the standard deduction => critical; up to this x standard => moderate
    // 2025 federal marginal brackets by filing status: [AGI lower bound, rate %]. Refresh each tax year.
    taxBrackets: {
      'Single':                    [[0,10],[11925,12],[48475,22],[103350,24],[197300,32],[250525,35],[626350,37]],
      'Married filing jointly':    [[0,10],[23850,12],[96950,22],[206700,24],[394600,32],[501050,35],[751600,37]],
      'Married filing separately': [[0,10],[11925,12],[48475,22],[103350,24],[197300,32],[250525,35],[375800,37]],
      'Head of household':         [[0,10],[17000,12],[64850,22],[103350,24],[197300,32],[250500,35],[626350,37]]
    }
  },

  // Legal / estate
  legal: {
    assetProtectionTrustThreshold: 5000000,  // assets above this with no asset-protection trust => liability risk
    reviewModerateYears: 3,                   // a document not reviewed in over 3 years => moderate concern (warn)
    reviewHighRiskYears: 5                     // not reviewed in over 5 years => high risk
  },

  // Overall score deductions (out of 100)
  score: { perRisk: 15, perWarn: 6 },

  // Per-category diminishing score: the first critical/moderate costs the most, each additional one less,
  // so a gauge isn't tanked by pile-on. Investments/legal: 1 critical ~67, 2 ~44, 3 ~21, 2 crit + 1 mod ~34,
  // 1 moderate ~90. Tax (gentler): 1 critical => 60, 2 => 45; 1 moderate => 85.
  categoryScoreScheme: {
    investments: { firstCritical: 30, addlCritical: 20, firstModerate: 10, addlModerate: 8 },
    retirement:  { firstCritical: 45, addlCritical: 20, firstModerate: 20, addlModerate: 10 },
    legal:       { firstCritical: 33, addlCritical: 23, firstModerate: 10, addlModerate: 8 },
    tax:         { firstCritical: 40, addlCritical: 15, firstModerate: 15, addlModerate: 8 }
  }
};
